system CopyOfsnow
{
    fast_forward                                1 1
    category                                    Nature
    technique 
    {
        visual_particle_quota                   2000
        material                                stone
        renderer                                Billboard
        {
            billboard_origin                    top_center
        }
        emitter                                 Box 
        {
            emission_rate                       3
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0
                max                             1
            }
            mass                                0
            velocity                            dyn_random
            {
                min                             1
                max                             4.5
            }
            all_particle_dimensions             dyn_random
            {
                min                             0
                max                             0.5
            }
            direction                           0 -1 0
            orientation                         0 0 0 0
            start_orientation_range             0 0 0 0
            end_orientation_range               0 0 0 0
            end_colour_range                    0 0 0 0
            colour                              0.501961 0.25098 0 1
            box_width                           5
            box_height                          0
            box_depth                           5
        }
        affector                                LinearForce WindLeft
        {
            enabled                             false
            force_vector                        -0.6 0 0
        }
        affector                                LinearForce WindRight
        {
            enabled                             false
            force_vector                        0.6 0 0
        }
    }
}
