LOCAL_C_INCLUDES := \
$(LOCAL_PATH)/../../IF/Classes \
$(LOCAL_PATH)/../../IF/Classes/controller \
$(LOCAL_PATH)/../../IF/Classes/Ext \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Base.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOCache \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOImageLoader \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOImageView \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Base \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer/Auto \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer/Back \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Header \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/MJRefresh.bundle \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/groupChat \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/mailList \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/oneChat \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/oneChat/chatCell \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/PopUpController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/UITabelViewController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/UIViewController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/en.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Host \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/images \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Images.xcassets \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Images.xcassets/AppIcon.appiconset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Images.xcassets/LaunchImage.launchimage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/DB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/view \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/zh-Hans.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/zh-Hant.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/AFNetworking \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/EMSDWebImage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/KZLInkLabel \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB/extra \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB/src \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/Helper \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/RegexKitLite \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS/Base.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS/Images.xcassets \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS/Images.xcassets/AppIcon.appiconset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS/Images.xcassets/LaunchImage.launchimage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/project.xcworkspace \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/project.xcworkspace/xcuserdata \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/project.xcworkspace/xcuserdata/mzc.xcuserdatad \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/project.xcworkspace/xcuserdata/mzc.xcuserdatad/xcdebugger \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata/mzc.xcuserdatad \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata/mzc.xcuserdatad/xcdebugger \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata/mzc.xcuserdatad/xcschemes \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata/tymacpro.xcuserdatad \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/WrapperChatIOS/WrapperChatIOS.xcodeproj/xcuserdata/tymacpro.xcuserdatad/xcschemes \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI/CCRichLabel \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI/WebView \
$(LOCAL_PATH)/../../IF/Classes/Ext/shaders \
$(LOCAL_PATH)/../../IF/Classes/model \
$(LOCAL_PATH)/../../IF/Classes/Net \
$(LOCAL_PATH)/../../IF/Classes/Net/command \
$(LOCAL_PATH)/../../IF/Classes/Net/command/alliance \
$(LOCAL_PATH)/../../IF/Classes/Net/push \
$(LOCAL_PATH)/../../IF/Classes/scene \
$(LOCAL_PATH)/../../IF/Classes/scene/battle \
$(LOCAL_PATH)/../../IF/Classes/scene/cropscene \
$(LOCAL_PATH)/../../IF/Classes/scene/dragon \
$(LOCAL_PATH)/../../IF/Classes/scene/loading \
$(LOCAL_PATH)/../../IF/Classes/scene/titan \
$(LOCAL_PATH)/../../IF/Classes/scene/world \
$(LOCAL_PATH)/../../IF/Classes/scene/world/map \
$(LOCAL_PATH)/../../IF/Classes/view \
$(LOCAL_PATH)/../../IF/Classes/view/dragonView \
$(LOCAL_PATH)/../../IF/Classes/view/fogView \
$(LOCAL_PATH)/../../IF/Classes/view/guide \
$(LOCAL_PATH)/../../IF/Classes/view/guiExt \
$(LOCAL_PATH)/../../IF/Classes/view/popup \
$(LOCAL_PATH)/../../IF/Classes/view/popup/achievement \
$(LOCAL_PATH)/../../IF/Classes/view/popup/alliance \
$(LOCAL_PATH)/../../IF/Classes/view/popup/CrossServiceActivity \
$(LOCAL_PATH)/../../IF/Classes/view/popup/DailyActive \
$(LOCAL_PATH)/../../IF/Classes/view/popup/dragonBattle \
$(LOCAL_PATH)/../../IF/Classes/view/popup/facebook \
$(LOCAL_PATH)/../../IF/Classes/view/popup/general \
$(LOCAL_PATH)/../../IF/Classes/view/popup/kingdom \
$(LOCAL_PATH)/../../IF/Classes/view/popup/Lottery \
$(LOCAL_PATH)/../../IF/Classes/view/popup/mail \
$(LOCAL_PATH)/../../IF/Classes/view/popup/TestFeedBack \
$(LOCAL_PATH)/../../IF/Classes/view/skill \
$(LOCAL_PATH)/../../IF/Classes/view/transition \
$(LOCAL_PATH)/../../IF/Classes/view/Widget \
$(LOCAL_PATH)/../../IF/libs/rapidxml \
$(LOCAL_PATH)/../../IF/libs/extensions \
$(LOCAL_PATH)/../../IF/libs/extensions/Adjust \
$(LOCAL_PATH)/../../IF/libs/extensions/Adjust/ADJAdditions \
$(LOCAL_PATH)/../../IF/libs/extensions/Adjust/AIAdditions \
$(LOCAL_PATH)/../../IF/libs/extensions/Appsflyer \
$(LOCAL_PATH)/../../IF/libs/extensions/crashhelper \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK/Deprecated \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK/DoubleClick \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/cs.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/de.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/en.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/es.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/fr.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/hu.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/id.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/it.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/ja.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/ko.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/nl.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/pt.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/ru.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/sl.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/th.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/tr.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/vi.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/zh-Hans.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSLocalization/zh-Hant.lproj \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSResources \
$(LOCAL_PATH)/../../IF/libs/extensions/HelpShift/helpshift-sdk-ios/HSThemes \
$(LOCAL_PATH)/../../IF/libs/extensions/inmobi \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle/images \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle/others \

