BASE_DIR_FOR_SCRIPT_SELF=$(cd "$(dirname "$0")"; pwd)

CCB_PROJECT_PATH=${BASE_DIR_FOR_SCRIPT_SELF}/../CCB/LuaCCB
TO_CCBI_PATH=${BASE_DIR_FOR_SCRIPT_SELF}/../IF/Resources/res/ccbi
TO_LUA_PATH=${BASE_DIR_FOR_SCRIPT_SELF}/../IF/Resources/src/ccbi

NBG_TOOLS_PATH=${BASE_DIR_FOR_SCRIPT_SELF}
cd ${NBG_TOOLS_PATH}/ccb/

python ccb.py ${CCB_PROJECT_PATH} ${TO_CCBI_PATH} ${TO_LUA_PATH}
